# Generated by Django 2.1.7 on 2019-04-03 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=12)),
                ('class_master', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=12)),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foreign_key.SchoolClass')),
            ],
        ),
    ]
